# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html

# Site
title: 杜鹃声
subtitle: '此情可待成追忆，只是当时已惘然'
description: 'AAAFORGE的技术博客'
keywords:
author: AAAFORGE
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
url: https://afogsheep.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Search
search:
  path: search.xml
  field: post
  content: true
  format: html

# Sitemap
sitemap:
  path: sitemap.xml
  rel: true
  tags: true
  categories: true

# Extensions
theme: fancy-avalanche

# Deployment
deploy:
  type: git
  repo: git@github.com:AFOGSHEEP/AFOGSHEEP.github.io.git
  branch: gh-pages
